---
title: "Uncertainty and Stochasticity in Caribou Demographic Parameters - DRAFT"
author: "Josie Hughes, Landscape Science & Technology Division, Environment & Climate Change Canada"
date: "July, 2021"
output: html_document
fig_caption: yes
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!require(bookdown)){install.packages("bookdown")}

devtools::load_all(".")
#library(caribouMetrics)
library(ggplot2)

covTableSim <- expand.grid(Anthro = seq(0, 90, by = 2), 
                           Fire = seq(0, 70, by = 10)) 
covTableSim$polygon = paste0("Missisa_", covTableSim$Anthro + 1)
covTableSim$area = "FarNorth"
covTableSim$Total_dist = covTableSim$Anthro + covTableSim$Fire
covTableSim$fire_excl_anthro = covTableSim$Fire
```


```{r}
#' @param replicates
#' @param modelVersion
#' @param survivalModelNumber
#' @param recruitmentModelNumber
#' @param Type
#' @param populationGrowthTable

popGrowthPars <- calcDemoParams(500,
                               modelVersion = "Johnson",
                               survivalModelNumber = "M1",
                               recruitmentModelNumber = "M4",
                               populationGrowthTable = read.csv("../data/populationGrowthTable.csv"))

popGrowthParsSmall <- calcDemoParams(35,
                                    modelVersion = "Johnson",
                                    survivalModelNumber = "M1",
                                    recruitmentModelNumber = "M4",
                                    populationGrowthTable = read.csv("../data/populationGrowthTable.csv"))

popGrowthParsInterannual <- calcDemoParams(5,
                                          modelVersion = "Johnson",
                                          survivalModelNumber = "M1",
                                          recruitmentModelNumber = "M4",
                                          populationGrowthTable = read.csv("../data/populationGrowthTable.csv"))
```

```{r}
rateSamples <- calcDemoPredictions(
  covTable = covTableSim,
  popGrowthPars = popGrowthParsSmall,
  ignorePrecision = FALSE,
  returnSample = TRUE,
  useQuantiles = TRUE,
  interannualVar = FALSE
)

rateSamplesInterannual <- calcDemoPredictions(
  covTable = covTableSim,
  popGrowthPars = popGrowthParsInterannual,
  ignorePrecision = FALSE,
  returnSample = TRUE,
  useQuantiles = TRUE,
  interannualVar = TRUE
)

rateSummaries <- calcDemoPredictions(
  covTable = covTableSim,
  popGrowthPars = popGrowthPars,
  ignorePrecision = FALSE,
  returnSample = FALSE,
  useQuantiles = FALSE,
  interannualVar = FALSE
)

rateSummariesIgnorePrecision <- calcDemoPredictions(
  covTable = covTableSim,
  popGrowthPars = popGrowthPars,
  ignorePrecision = TRUE,
  returnSample = FALSE,
  useQuantiles = FALSE,
  interannualVar = FALSE
)
```

```{r}
theme_set(theme_bw())

rateSamples$S_PIlow = 1
rateSamples$S_PIhigh = 1
rateSamples$rep = as.factor(rateSamples$replicate)
levels(rateSamples$rep) = sample(unique(rateSamples$replicate), 
                                 replace = FALSE)
rateSamples$rep = as.character(rateSamples$rep)

rateSamplesInterannual$S_PIlow = 1
rateSamplesInterannual$S_PIhigh = 1
rateSamplesInterannual$rep = as.factor(rateSamplesInterannual$replicate)
levels(rateSamplesInterannual$rep) = sample(unique(rateSamplesInterannual$replicate), 
                                            replace = FALSE)
rateSamplesInterannual$rep = as.character(rateSamplesInterannual$rep)
rateSamples$R_PIlow = 1
rateSamples$R_PIhigh = 1
rateSamples$fullGrp = paste(rateSamples$rep, rateSamples$Fire)

rateSamplesInterannual$R_PIlow = 1
rateSamplesInterannual$R_PIhigh = 1
rateSamplesInterannual$fullGrp = paste(rateSamplesInterannual$rep,
                                       rateSamplesInterannual$Fire)
```

```{r parameterUncertaintyOnly,echo=FALSE, fig.width=12, fig.height=5,fig.cap="Johnson 2020 model with parameter uncertainty but no precision. As far as we understand, this is what is happening in the Michelleti et al. implementation - except we included uncertainty about the intercept because we don't understand why that would be omitted. Also note the bands here are 2.5% and 97.5% quantiles rather than standard deviations."}

base1 <- ggplot(data = rateSummariesIgnorePrecision, 
                aes(x = Anthro, y = S_bar, ymin = S_PIlow, ymax = S_PIhigh))+
  geom_line(colour = "black", size = 2)+
  geom_ribbon(alpha = 0.25)+
  xlab("Anthropogenic Disturbance (%)")+
  ylab("Adult Female Survival")+
  scale_y_continuous(limits = c(0.65, 1))+
  theme(legend.position = "none") +
  scale_x_continuous(limits = c(0, 90), breaks = c(0, 20, 40, 60, 80))

base1

plot_recruitment3 <- ggplot(
  data = rateSummariesIgnorePrecision, 
  aes(x = Anthro, y = R_bar * 100, group = Fire, colour = Fire, type = Fire, 
      ymin = R_PIlow * 100, ymax = R_PIhigh * 100, fill = Fire)
  )+
  geom_line(size = 2)+
  geom_ribbon(alpha = 0.15, colour = NA)+
  scale_fill_gradient(low = "green", high = "red")+
  scale_colour_gradient(low = "green", high = "red")+
  scale_y_continuous(limits = c(0, 60), breaks = c(0, 10, 20, 30, 40, 50, 60))+
  scale_x_continuous(limits = c(0, 90), breaks = c(0, 20, 40, 60, 80))+
  xlab("Anthropogenic disturbance (%)")+
  ylab("Recruitment (calves per 100 cows)")
plot_recruitment3

```
```{r withPrecision,echo=FALSE, fig.width=12, fig.height=5,fig.cap="Johnson 2020 model with parameter uncertainty and precision. Faint coloured lines show example trajectories of expected demographic rates in sample populations, assuming each sample populations are randomly distributed among quantiles of the beta distribution, and each population remains in the same quantile of the beta distribution as disturbance changes over time. Interannual variability is not included."}

base1 <- ggplot(data = rateSummaries, 
                aes(x = Anthro, y = S_bar, ymin = S_PIlow, ymax = S_PIhigh))+
  geom_line(data = subset(rateSamples, Fire == 0), size = 0.5, 
            aes(x = Anthro, y = S_bar, group = rep, colour = rep))+
  geom_line(colour = "black", size = 2)+
  geom_ribbon(alpha = 0.25)+
  xlab("Anthropogenic Disturbance (%)")+
  ylab("Adult Female Survival")+
  scale_y_continuous(limits = c(0.65, 1))+
  theme(legend.position = "none")+
  scale_x_continuous(limits = c(0, 90), breaks = c(0, 20, 40, 60, 80))

base1

plot_recruitment3 <- ggplot(data = rateSummaries, 
                            aes(x = Anthro, y = R_bar * 100,  group = Fire,
                                colour = Fire, type = Fire))+
  geom_line(data = rateSamples,  
            aes(x = Anthro, y = R_bar * 100, group = fullGrp, colour = Fire),
            size = 0.5, alpha = 0.2)+
  geom_line(size = 2)+
  scale_colour_gradient(low = "green", high = "red")+
  scale_y_continuous(limits = c(0, 60),
                     breaks = c(0, 10, 20, 30, 40, 50, 60))+
  scale_x_continuous(limits = c(0, 90), breaks = c(0, 20, 40, 60, 80))+
  xlab("Anthropogenic disturbance (%)")+
  ylab("Recruitment (calves per 100 cows)")
plot_recruitment3

```

```{r withInterannualVariability,echo=FALSE, fig.width=12, fig.height=5,fig.cap="Johnson 2020 model with parameter uncertainty, precision and interannual variability. Faint coloured lines show example trajectories of expected demographic rates in sample populations, assuming each sample populations are randomly distributed among quantiles of the beta distribution, and each population remains in the same quantile of the beta distribution as disturbance changes over time. I have lifted interannual variability parameters from Glenn's SpaDES module, and have no confidence that the values are appropriate."}

base3 <- ggplot(data = rateSummaries, 
                aes(x = Anthro, y = S_bar, ymin = S_PIlow, ymax = S_PIhigh))+
  geom_line(data = subset(rateSamplesInterannual, Fire == 0), size = 0.5,
            aes(x = Anthro, y = S_bar, group = rep, colour = rep))+
  geom_line(colour = "black", size = 2)+
  geom_ribbon(alpha = 0.25)+
  xlab("Anthropogenic Disturbance (%)")+
  ylab("Adult Female Survival")+
  scale_y_continuous(limits = c(0.5, 1))+
  theme(legend.position = "none")+
  scale_x_continuous(limits = c(0, 90), breaks = c(0, 20, 40, 60, 80))
base3

plot_recruitment2 <- ggplot(data = rateSummaries, 
                            aes(x = Anthro, y = R_bar * 100, group = Fire,
                                colour = Fire, type = Fire))+
  geom_line(data = rateSamplesInterannual, 
            aes(x = Anthro, y = R_bar * 100, group = fullGrp, colour = Fire),
            size = 0.5, alpha = 0.1)+
  geom_line(size = 2)+
  scale_colour_gradient(low = "green", high = "red")+
  scale_y_continuous(limits = c(0, 100), breaks = 0:10*10)+
  scale_x_continuous(limits = c(0, 90), breaks = c(0, 20, 40, 60, 80))+
  xlab("Anthropogenic disturbance (%)")+
  ylab("Recruitment (calves per 100 cows)")+
  coord_cartesian(ylim = c(0,60))
plot_recruitment2

```
